project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "MetabolismGraph"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Model"
        href: model.qmd
      - text: "GNN-LLM-Memory"
        href: gnn-llm-memory.qmd
      - text: "Results"
        href: results.qmd
      - text: "References"
        href: references.qmd
    tools:
      - icon: github
        href: https://github.com/allierc/MetabolismGraph
  page-footer: "Copyright 2025, CÃ©dric Allier"
  repo-url: https://github.com/allierc/MetabolismGraph/
  site-url: https://allierc.github.io/MetabolismGraph/

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    code-fold: show
    code-overflow: wrap
    code-tools:
      source: repo
    mermaid:
      theme: neutral
